import { Event } from '@/lib/types';

const catalogCreatedAt = '2026-02-26T00:00:00+05:30';

export const EVENT_CATALOG: Event[] = [
    {
        id: '10000000-0000-0000-0000-000000000001',
        name: 'Prompt2Website: The Vibe Coding Challenge',
        slug: 'prompt2website-the-vibe-coding-challenge',
        description: 'Turn prompts into powerful websites.',
        long_description: 'AI Website Building challenge where each participant builds a complete website from a given problem statement within a limited time and presents the final output to judges.',
        category: 'technical',
        fee: 5000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Computer Lab 1',
        rules: [
            'Each participant must build a website based on the given problem statement within 1 hour.',
            'Internet access is allowed.',
            'Use of AI tools (ChatGPT, GitHub Copilot, etc.) is allowed.',
            'Participants may use any programming language or technology stack.',
            'Pre-built full projects, GitHub cloning, or previously developed projects are strictly not allowed.',
            'The website must be developed completely during the competition time.',
            'After completion, each participant must present their project for 2–3 minutes.',
            'Judges may ask questions regarding code, logic, and functionality.',
            'If a participant is unable to explain their code properly, marks will be reduced.',
            'The decision of judges will be final and binding.',
            'Participation: Solo participants only.',
            'Duration: 1 hour.',
        ],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000002',
        name: 'TypeSprint: The Ultimate Typing Showdown',
        slug: 'typesprint-the-ultimate-typing-showdown',
        description: 'Fast fingers. Faster victory.',
        long_description: 'Typing Competition event focused on speed and precision where participants compete on organizer-selected software with scoring based on WPM and accuracy.',
        category: 'technical',
        fee: 8000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Computer Lab 2',
        rules: [
            'The typing test will be conducted using organizer-selected typing software.',
            'Each participant will get only one attempt to complete the test.',
            'Participants must type the given text exactly as shown on the screen.',
            'The use of mobile phones, external help, or unfair means is strictly prohibited.',
            'Participants must use the keyboard and system provided by the organizers (or assigned system).',
            'The final score will be based on Typing Speed (WPM) and Accuracy (%).',
            'In case of a tie, the participant with higher accuracy will be given preference.',
            'Participants must follow all instructions given by the event coordinators.',
            'Any form of misconduct may lead to disqualification.',
            'The decision of the organizers will be final.',
            'Participation: Solo participants only.',
            'Duration: 1-2 hours.',
        ],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000003',
        name: 'QuizStorm: Battle of Brains',
        slug: 'quizstorm-battle-of-brains',
        description: 'Where knowledge meets competition.',
        long_description: 'A competitive quiz event designed to test knowledge, speed, logic, and presence of mind in a fun and engaging format with separate Solo and Duo tracks.',
        category: 'technical',
        fee: 4000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Computer Lab 2',
        rules: [
            'Participation is open to all students in Solo and Duo categories.',
            'Entry fee: Solo ₹40, Duo ₹80 (calculated at ₹40 per participant).',
            'Duration: 1-2 hours.',
            'The quiz consists of 3 rounds: Round 1 (Elimination), Round 2 (Score Based), Round 3 (Final Showdown).',
            'Round 1 – Brand Vision (Logo Identification): identify logos of tech companies and popular brands; top 50% qualify for Round 2.',
            'Round 2 – Rapid Recall (Rapid Fire): each participant gets 60 seconds to answer maximum questions; pass is allowed; top scorers move to Final Round.',
            'Round 3 – Final Face-Off (Guess the Image): identify personalities, gadgets, apps, products, or technologies from images; tie-breaker question in case of tie.',
            'Judging criteria: total score across rounds, accuracy of answers, and final round performance.',
            'Solo and Duo quiz events will be conducted separately with different sets of questions.',
        ],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 2,
        team_size_fixed: null,
        team_size_min: 1,
        team_size_max: 2,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000004',
        name: 'CanvaCraft: The Poster Design Challenge',
        slug: 'canvacraft-the-poster-design-challenge',
        description: 'Design. Create. Dominate.',
        long_description: 'Poster Designing (Canva) event where participants create a theme-based A4 poster within 90 minutes using Canva only.',
        category: 'technical',
        fee: 5000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Computer Lab 1',
        rules: [
            'Individual participation only.',
            'Entry fee: ₹50 / ₹99 as per organizer category.',
            'Duration: 90 minutes.',
            'Each participant can submit only one poster.',
            'The design must be created using Canva only.',
            'Participants may use online resources and AI tools for design assistance.',
            'Pre-defined Canva templates are not allowed.',
            'The theme will be announced on the spot.',
            'Copying from other participants will lead to disqualification.',
            'Poster specification: Rectangle layout.',
            'Poster size: A4 (2480 × 3508 px).',
            'Accepted file formats: PNG / JPG.',
            'Marking scheme (30 marks): Creativity and Innovation (10), Relevance to Theme (10), Color Combination & Layout (5), Typography & Clarity (5).',
        ],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000006',
        name: 'NrityaVerse',
        slug: 'nrityaverse',
        description: 'Where tradition meets limitless expression.',
        long_description: 'Celebrate creativity, expression, and performance in this flagship dance competition.',
        category: 'cultural',
        fee: 20000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-25 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Main Stage',
        rules: [
            'Event Coordinator: Diya Nemade (Lead)',
            'Entry Fee: ₹200 (Solo) / ₹400 (Group)',
            'Duration: 3-6 Minutes',
            'Individual performance (Solo) and 4–6 participants (Group).',
            'Any dance style allowed.',
            'Props allowed (optional).',
            'Participants must submit their music in advance.',
            'Participants must report 30 minutes before their event.',
            'Judges’ decision will be final and binding.',
            'Any inappropriate content will lead to disqualification.',
            'Certificates will be provided to all the participants.',
        ],
        prize_text: 'Solo: Winner- Gold Medal + Cash (2000) + Certificate | Runner Up- Silver Medal + Cash (1000) + Certificate. Group: Winner- Trophy + Cash (3000) + Certificate | Runner Up- Trophy + Cash (1000) + Certificate',
        prize_winner: 200000,
        prize_runner_up: 100000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 6,
        team_size_fixed: null,
        team_size_min: 1,
        team_size_max: 6,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000007',
        name: 'SurTarang',
        slug: 'surtarang',
        description: 'Ride the waves of melody.',
        long_description: 'Singing competition for Solo and Group participants celebrating melody, performance, and expression.',
        category: 'cultural',
        fee: 20000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-25 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Seminar Hall',
        rules: [
            'Event Coordinator: Prerna Dikondwar (Lead)',
            'Entry Fee: ₹200 (Solo) / ₹400 (Group)',
            'Duration: 3-6 Minutes',
            'Any language allowed.',
            'Participants must bring their own instruments if required.',
            'Karaoke tracks must be submitted prior to the event.',
            'Group must have minimum 3 and maximum 8 members.',
            'Judges’ decision will be final and binding.',
            'Certificates will be provided to all the participants.',
        ],
        prize_text: 'Solo: Winner – Gold Medal + Cash (2500) + Certificate | Runner Up- Silver Medal + Cash (1000) + Certificate. Group: Winner – Trophy + Cash (3000) + Certificate | Runner Up- Cash (1500) + Certificate',
        prize_winner: 250000,
        prize_runner_up: 100000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 8,
        team_size_fixed: null,
        team_size_min: 1,
        team_size_max: 8,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000001',
        name: 'Badminton',
        slug: 'badminton',
        description: 'Lead: Akansha Belote. Solo badminton tournament (Male/Female).',
        long_description: null,
        category: 'sports',
        fee: 15000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Sports Court',
        rules: [
            'Participation: 1 (male/female).',
            'Service must be underarm.',
            'Shuttle must be below the waist.',
            'Both feet must stay inside the service court.',
            'If player\'s score is even (0,2,4…) → serve from right side.',
            'If score is odd (1,3,5…) → serve from left side.',
            'Fault Rules: Point will be given to opponent if:',
            'Shuttle lands outside boundary line.',
            'Shuttle hits net and does not cross.',
            'Player touches the net.',
            'Shuttle touches player\'s body.',
            'Double hit or illegal stroke.',
        ],
        prize_text: 'Winner: ₹1,500 | Runner Up: ₹700',
        prize_winner: 150000,
        prize_runner_up: 70000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000002',
        name: 'Box Cricket',
        slug: 'box-cricket',
        description: 'Lead: Sahil Naik. Competitive box cricket tournament.',
        long_description: null,
        category: 'sports',
        fee: 95000,
        fee_calculation: 'per_team',
        max_participants: 300,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Cricket Ground',
        rules: [
            'Participation: Team 7 member.',
            'Match Format: Knockout format (losing team eliminated).',
            'Each innings consists of 5 overs.',
            'In case of tie, Super Over will be played.',
            'Toss: Winning captain chooses to bat or bowl first. Decision cannot be changed.',
            'Team Composition: Each team must have 6 players. 5 different bowlers must bowl 1 over each.',
            'Fielding side: 1 wicket keeper, 1 bowler, 4 fielders.',
            'Batting: Two batsmen must be present on the pitch. All players must bat before innings closure (unless all out).',
            'Standard running between wickets allowed.',
            'Bowling: 5 bowlers compulsory (1 over each). 6 legal balls per over.',
            'No Ball Rules: Line No Ball (stepping on or crossing bowling crease) or Overstep No Ball (crossing popping crease). 1 run penalty + re-bowl.',
            'Fielding: 4 fielders inside designated box area. No Powerplay. Fielders must stay inside boundary limits.',
            'Umpire’s decision is final and binding. Misconduct may lead to suspension.',
            'Tie & Super Over: 1 over Super Over. 3 batsmen allowed. 1 bowler. If still tied, team with more boundaries wins.',
        ],
        prize_text: 'Winner: ₹5,000 | Runner Up: ₹3,000',
        prize_winner: 500000,
        prize_runner_up: 300000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 7,
        team_size_fixed: 7,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000003',
        name: 'Volleyball',
        slug: 'volleyball',
        description: 'Lead: Tejas Natekar. High-intensity volleyball competition.',
        long_description: null,
        category: 'sports',
        fee: 60000,
        fee_calculation: 'per_team',
        max_participants: 300,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Volleyball Court',
        rules: [
            'Participation: 6 players per team.',
            'College ID Card is Compulsory for every participant.',
            '6 players on the court at any one time - 3 in the front row and 3 in the back row. Maximum of 3 hits per side.',
            'Points are made on every serve for winning team of rally (rally-point scoring).',
            'Player may not hit the ball twice in succession (block is not considered a hit).',
            'Ball may be played off the net during a volley and on a serve.',
            'Out conditions: hits antennae/net post, floor outside court, net/cables outside antennae, referee stand, ceiling above nonplayable area.',
            'It is legal to contact the ball with any part of a player\'s body.',
            'It is illegal to catch, hold or throw the ball.',
            'A player cannot block or attack a serve from on or inside the 10-foot line.',
            'Matches are made up of sets. 3-set matches are of 15 points.',
            'Each set must be won by two points. The winner is the first team to win 2 sets.',
        ],
        prize_text: 'Winner: ₹2,500 | Runner Up: ₹1,500',
        prize_winner: 250000,
        prize_runner_up: 150000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 6,
        team_size_fixed: 6,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000004',
        name: 'Tug of war',
        slug: 'tug-of-war',
        description: 'Lead: Rohan Waghmode. Traditional rope pulling challenge.',
        long_description: null,
        category: 'sports',
        fee: 50000,
        fee_calculation: 'per_team',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Main Ground',
        rules: [
            'Participation: 7 Team Member.',
            'Two team compete against each other. College id is compulsory.',
            'Rope Setup: A long rope with a centre mark. mark must be over the line.',
            'Objective: Pull the opposing team so the centre mark crosses your side’s boundary line.',
            'Start: Players hold rope with hands. Teams start on referee’s signal.',
            'Fouls: Sitting or lying down while pulling. Wrapping rope around body/arm. Sudden jerks before signal. Using gloves.',
        ],
        prize_text: 'Winner: ₹2,500 | Runner Up: ₹1,500',
        prize_winner: 250000,
        prize_runner_up: 150000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 7,
        team_size_fixed: 7,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000005',
        name: 'Chess',
        slug: 'chess',
        description: 'Lead: Suraj Suryawanshi. Strategy and focus showdown.',
        long_description: null,
        category: 'sports',
        fee: 20000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Indoor Hall',
        rules: [
            'Game time will be 15 minutes.',
            'Black and white decided by coin toss 2 minutes prior.',
            'First touch move: touching a piece requires moving it. Warning then disqualification.',
            'No phones, digital watches, or other smart devices. No talking.',
            'All games are knockout games.',
            'Illegal moves: Warning then Loss of game.',
            'Draw: Stalemate, Insufficient material, or 3-fold repetition.',
            'After Draw: Blitz playoff (5 min each). Still Draw: White 5 min, Black 4 min (Black wins if draw).',
            'College ID is compulsory.',
        ],
        prize_text: 'Winner: ₹1,500 | Runner Up: ₹800',
        prize_winner: 150000,
        prize_runner_up: 80000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000006',
        name: 'Carrom',
        slug: 'carrom',
        description: 'Lead: Suraj Suryawanshi. Precision and control on the board.',
        long_description: null,
        category: 'sports',
        fee: 10000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Indoor Hall',
        rules: [
            'Entry Fee: 100 for single player / 200 for team match.',
            'College I-card is compulsory. Using thumb is not allowed.',
            'Toss decides who starts. Winner chooses white or black.',
            'Queen Rule: Must be pocketed first then covered by pocketing your own coin. If not covered, queen returns to center.',
            'Score: 1 point per coin, 3 points for queen.',
            'Fouls: Striker pocketed, pocketing opponent’s coin, striker leaves board, touching coin with hand.',
        ],
        prize_text: 'Singles – Winner: ₹1,000 | Runner Up: ₹500. Doubles – Winner: ₹2,000 | Runner Up: ₹600.',
        prize_winner: 200000,
        prize_runner_up: 60000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 2,
        team_size_fixed: null,
        team_size_min: 1,
        team_size_max: 2,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000007',
        name: 'Ludo',
        slug: 'ludo',
        description: 'Lead: Suraj Suryawanshi. Casual board game tournament.',
        long_description: null,
        category: 'sports',
        fee: 5000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Indoor Hall',
        rules: [
            'Individual format. All matches are knockout.',
            'First player to move all 4 tokens home wins.',
            'Token entrance requires rolling a 6. Rolling 6 gives extra turn. 3 consecutive 6s cancel turn.',
            'Landing on opponent’s single token sends it back to start.',
            'Safe/star positions cannot be captured.',
            'Exact number required to enter home triangle.',
            'Knockout matches are Best of 3 games.',
            'No phones or outside help. Referee decision is final.',
        ],
        prize_text: 'Winner: ₹500',
        prize_winner: 50000,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000008',
        name: 'BGMI',
        slug: 'bgmi',
        description: 'Lead: Mahesh Khune. Elite squad battle royale.',
        long_description: null,
        category: 'sports',
        fee: 30000,
        fee_calculation: 'per_team',
        max_participants: 300,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'E-Sports Arena',
        rules: [
            'Participation: 4 player squad. I card is compulsory.',
            'Only mobile devices allowed.',
            'No cheating, hacking, or scripts. Teaming is prohibited.',
            'Carry your own accessories (chargers/earphones).',
            'Reach venue 30 mins early. Late joining not allowed.',
            'Presence at the venue is mandatory.',
        ],
        prize_text: 'Winner: ₹2,500 | Runner Up: ₹1,500',
        prize_winner: 250000,
        prize_runner_up: 150000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 4,
        team_size_fixed: 4,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000009',
        name: 'Deadlift',
        slug: 'deadlift',
        description: 'Lead: Pratik More. Test your raw strength.',
        long_description: null,
        category: 'sports',
        fee: 10000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Fitness Arena',
        rules: [
            'Individual knockout format. 3 attempts per match.',
            'Highest successful lift counted.',
            'Bar must be lifted to full upright position. Knees and hips fully locked.',
            'No hitching or resting bar on thighs. Bar must be lowered under control.',
            'Lifting belt only if permitted. No belts/gloves unless allowed.',
            'Referee decision is final.',
        ],
        prize_text: 'Winner: ₹1,500 | Runner Up: ₹800',
        prize_winner: 150000,
        prize_runner_up: 80000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000010',
        name: 'Bench Press',
        slug: 'bench-press',
        description: 'Lead: Pratik More. Pushing to the limit.',
        long_description: null,
        category: 'sports',
        fee: 10000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-24 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Fitness Arena',
        rules: [
            'Individual knockout format. 3 attempts per match.',
            'Highest successful lift counted.',
            'Lift must start with bar at chest and pressed until arms are fully locked.',
            'No bouncing bar on chest. Hips and shoulders must remain on bench. Feet flat.',
            'No belts/gloves unless allowed.',
            'Referee decision is final.',
        ],
        prize_text: 'Winner: ₹1,500 | Runner Up: ₹800',
        prize_winner: 150000,
        prize_runner_up: 80000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
];

export function getActiveEvents(): Event[] {
    return EVENT_CATALOG
        .filter((event) => event.is_active)
        .sort((a, b) => new Date(a.event_date).getTime() - new Date(b.event_date).getTime());
}

export function getEventById(eventId: string): Event | undefined {
    return EVENT_CATALOG.find((event) => event.id === eventId && event.is_active);
}

export function getEventBySlug(slug: string): Event | undefined {
    return EVENT_CATALOG.find((event) => event.slug === slug && event.is_active);
}

export function getEventsByIds(eventIds: string[]): Event[] {
    const idSet = new Set(eventIds);
    return getActiveEvents().filter((event) => idSet.has(event.id));
}
